### ISSUE TITLE
宝塔+nginx+php无法测速

### ISSUE THREAD

**Issue by zhangyuchen813** [BadApple9/speedtest-x#10]
~~无法测速，结果也无法查看，显示：数据接口请求异常：parsererror
不知道是不是我配置有问题噢。~~

重新部署了一下，默认配置，测速页面显示IP底地方获取不到IP和位置，要等好久才开始测速。
问题如下：
默认config.php中是“ip.sb” 无法获取IP，显示“Unknown”
改成“ipinfo.io”后正常，可获取ip位置。

**Comment by zhangyuchen813** [comment]
重新部署了一下，测速页面显示IP底地方获取不到IP和位置，要等好久才开始测速。
问题如下：
默认config.php中是“ip.sb” 无法获取IP
改成“ipinfo.io”后正常。

**Comment by BadApple9** [comment]
小部分机房网络无法连通 ip.sb，这种情况一般更换为 ipinfo.io 即可。

后续我会把这种问题整理到 Wiki 里，感谢关注。
