### ISSUE TITLE
Docker获取不到IP地址

### ISSUE THREAD

**Issue by zhouliang** [BadApple9/speedtest-x#11]
Docke方式部署，获取IP地址错误：

IP地址: 172.17.0.1 - private IPv4 access

**Comment by BadApple9** [comment]
有加 nginx 之类的前置代理吗？

**Comment by zhouliang** [comment]
跟NGINX无关。Docker有自己的内网，你在getClientIp()用$_SERVER只能获取到内网地址，拿不到公网IP的。建议直接通过http://ip.sb/获取IP地址。

**Comment by BadApple9** [comment]
所以你的环境是什么？只是单纯部署了这个容器然后直接用 ip:port 公网访问的吗？

**Comment by zhouliang** [comment]
> 所以你的环境是什么？只是单纯部署了这个容器然后直接用 ip:port 公网访问的吗？
> 本镜像父容器自带的 Apache 是能够转发客户端真实 IP 给 PHP 的。

对的。只部署这个容器，用 ip:port访问。未安装nginx。

**Comment by BadApple9** [comment]
能否提供下你的操作系统信息？
因为无论是我自身测试还是其他用户使用 docker 部署，暂未发现获取的 IP 是容器网关地址的情况。

另外，你可以临时这样解决，启动容器时指定容器网络模式为 `host`：
`docker run -d --net=host -p 9001:80 -it badapple9/speedtest-x`

**Comment by zhouliang** [comment]
参考：https://github.com/docker/for-mac/issues/180，docker默认的桥接模式应该都有这个问题。
host模式可以解决这个问题，但该模式下端口映射无效，需要容器环境变量支持自定义访问端口，不然独占80端口，其他web服务都用不了了。

**Comment by BadApple9** [comment]
是用 macOS 部署的吗，运行在 Linux 上还未发现有这个问题。

**Comment by zhouliang** [comment]
那个issues说的是mac，我是CentOS。

**Comment by BadApple9** [comment]
> 参考：[docker/for-mac#180](https://github.com/docker/for-mac/issues/180)
> 
> docker默认的桥接模式应该都有这个问题。
> 
> host模式可以解决这个问题，但该模式下端口映射无效，需要容器环境变量支持自定义访问端口，不然独占80端口，其他web服务都用不了了。

容器支持自定义访问端口，启动时传 `WEBPORT` 变量。 

`docker run -d -e WEBPORT=8080 --net=host -p 8080:8080 -it badapple9/speedtest-x`

先将就着这样解决吧，后续我看是否还有相同案例。
目前来看是个例情况，镜像已经有 4600+ 次拉取，还未收到类似反馈。
