### ISSUE TITLE
之前在别的机器部署docker没有问题，今天部署发现apache报错

### ISSUE THREAD

**Issue by wwhQAQ** [BadApple9/speedtest-x#14]
![image](https://user-images.githubusercontent.com/21196152/101859590-f7076900-3ba6-11eb-8e02-bf08450dc385.png)
不知是不是我配置问题。。

**Comment by BadApple9** [comment]
提供一下你启动容器的命令吧，我排查下。

**Comment by wwhQAQ** [comment]
谢谢回复：），我是用教程的启动命令，
![image](https://user-images.githubusercontent.com/21196152/101883443-39926b00-3bd2-11eb-8fb4-3c3365f4d42f.png)
![image](https://user-images.githubusercontent.com/21196152/101883792-b58cb300-3bd2-11eb-881c-220d945398c9.png)

**Comment by BadApple9** [comment]
我排查了下，这个不能算 apache 的报错，只能算警告。
大概意思是没有给运行在 apache 上的测速站点设定一个域名。
因为我们容器内站点直接监听 ip:port，不需要设定域名，所以可以忽略这条警告，不影响正常使用。

**Comment by BadApple9** [comment]
如果不能正常使用，可以告知我其他的具体表现和截图。
（可以确定的是，上述的 apache 警告是不影响使用的，因为大家运行容器时都会有这条警告）

**Comment by wwhQAQ** [comment]
感谢解答 :+1: :100:
