### ISSUE TITLE
添加限制测速次数选项

### ISSUE THREAD

**Issue by am-abudu** [BadApple9/speedtest-x#15]
建议添加限制测速次数选项，防止小鸡流量被刷爆

**Comment by zhangyuchen813** [comment]
> 建议添加限制测速次数选项，防止小鸡流量被刷爆

为何要公开你的地址给别人测呢？留着自己测不就行了吗？
既然你公开了链接，又要限制。。。

**Comment by BadApple9** [comment]
感谢你的关注。

你提到的功能我会认真考虑，如果未来的版本中增加了这个功能，我会在本 issue 中回复，谢谢。
