### ISSUE TITLE
大佬build docker的時候是不是忘了把chartjs資料夾放進去?

### ISSUE THREAD

**Issue by HuJK** [BadApple9/speedtest-x#19]
大佬build docker的時候是不是忘了把chartjs資料夾放進去?

docker image裡面沒有這個資料夾

btw. Chart.min.js 的cdn文件我找到這個 https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js ，但是util.js我就沒找到了。這2個都是從官方範例抄過來的

**Comment by BadApple9** [comment]
抱歉，是我疏漏了，已经修复。
原定使用 ChartJS 的 CDN，但我也没找到 `util.js` 的 CDN 地址，索性就都没有用了。

再次感谢你的贡献。
