### ISSUE TITLE
刷流量漏洞

### ISSUE THREAD

**Issue by linailin** [BadApple9/speedtest-x#2]
这玩意能被人刷流量，
例如
100M    http://xxxxx.com/backend/garbage.php?ckSize=100  
1000M    http://xxxxx.com/backend/garbage.php?ckSize=1000

**Comment by BadApple9** [comment]
感谢你的关注。

因为要测试出服务器的真实带宽，必然要从服务端生成无用文件来测试下行，所以这不算个漏洞，但存在被人恶意利用的可能，这无法避免。

稍后我会在项目介绍里标明风险点，存在被人恶意刷流量的可能，如果被恶意攻击，注意要及时关掉测速服务。
