### ISSUE TITLE
大佬，ip库还有没有别的选择？

### ISSUE THREAD

**Issue by sunnynctu** [BadApple9/speedtest-x#22]
默认的ip.sb和ipinfo.io都不准确，把我这里移动识别为广东移动，联通识别为辽宁联通，电信识别为陕西榆林电信，教育网则不识别具体地址，没有一个正确的。

**Comment by sunnynctu** [comment]
我这里的IP地址，国内的ip138.com，ip.cn，站长之家都能准确识别

**Comment by BadApple9** [comment]
ip138.com，ip.cn 没有免费的 API 可以用。

目前只支持 ip.sb 和 ipinfo.io，更多的免费 IP API 服务需要我探索下。
