### ISSUE TITLE
大佬，IP记录能否完整显示局域网设备IP？

### ISSUE THREAD

**Issue by hzjixiang** [BadApple9/speedtest-x#23]
局域网测试不同设备的最大速度，最后发现网址主机位被影藏了，很不方便记录参考

**Comment by BadApple9** [comment]
目前程序还不支持可配置，但可以改代码实现，修改 `backend/report.php` 的第 `26` 行，将
```"ip" => maskLastSegment(filter_var($_POST['ip'], FILTER_SANITIZE_STRING)),```
修改为
```"ip" => filter_var($_POST['ip'], FILTER_SANITIZE_STRING)```
