### ISSUE TITLE
DD萌咖debian9系统，安装锐速后，部署docker版运行不正常

### ISSUE THREAD

**Issue by GloryBoy239** [BadApple9/speedtest-x#24]
大佬，问题RT。不正常的表现为2点：
1、点击Start开始，出现“假死”，得等上1分来钟，才开始显示IP，跑测速；
2、IP运营商不能正常获取，显示 Unknown。

——以上我在6、7台小鸡上部署，都出现了这种问题。对了，我用的系统是DD的debian 9。

经过一步步测试发现：
1、主机商原Debian9系统不改内核：Start反应很快，IP识别正常
2、部分主机商原Debian9系统换锐速内核：Start反应很快，IP识别正常
3、更换萌咔Debian9系统不改内核：Start反应很快，IP识别正常
4、更换萌咔Debian9系统更换锐速内核：Start反应1分钟，IP识别不到运营商和位置。

能否指导下，怎么查看问题出在哪

**Comment by BadApple9** [comment]
你好，我手上缺少「更换萌咔Debian9系统更换锐速内核」这样的主机环境，能否提供此环境的小鸡供我测试一下吗。

可以联系我的 TG：[@xz996](http://t.me/xz996)

**Comment by GloryBoy239** [comment]
> 你好，我手上的东西「更换萌咔Debian9系统更换锐速内核」这样的主机环境，能否提供此环境的小鸡供我测试一下吗。
> 
> 可以联系我的TG：[@ xz996](http://t.me/xz996)

哈哈哈，当然没问题。我联系你

**Comment by BadApple9** [comment]
已解决

**Comment by reworld** [comment]
> 已解决

大佬解决方法复杂不，我也遇到了。
