### ISSUE TITLE
获取不了IP运营商和城市

### ISSUE THREAD

**Issue by iammeken** [BadApple9/speedtest-x#26]
可以获得公网IP：

IP地址: aa.bb.cc.dd - Unknown

2个IP库都如此，请问会是什么原因？

源站IP被地址库拉黑？

**Comment by BadApple9** [comment]
docker 部署的吗？如果是，我猜测是容器内网络和宿主机通信有问题。
什么系统内核？有安装锐速之类的东西吗？

**Comment by yiguihai** [comment]
数据接口请求异常：parsererror

**Comment by qeqeq1** [comment]
IP地址: 172.17.0.1 - private IPv4 access，今天测速都是这个地址，上星期没事 
会不会与我测试了WARP有关系？
