### ISSUE TITLE
local .js auto start?

### ISSUE THREAD

**Issue by webresurs** [BadApple9/speedtest-x#27]
Подскажете как автоматически запускать speedtest-x на сайте? 
например через js...

Хочу тестировать локальную сеть...
----------------------------------------------------------------------------

Can you tell me how to automatically run speedtest-x on the site?
for example via js ...

I want to test a local network ...

**Comment by BadApple9** [comment]
I'm sorry I didn't quite understand what you said.

If you want to deploy it easily, you can use Docker pull its image and run it.

**Comment by webresurs** [comment]
Хочу установить на внутренний сайт, как счетчик для сбора статистики по скорости с компьютеров в сети. скрытно.
--------------------------------------------------------------------------------------------
I want to install it on an internal site as a counter for collecting speed statistics from computers on the network. secretly .


```
 <script type="text/javascript">
    document.querySelector('#startStopBtn').addEventListener('click', () => {console.log('clicked')});
    document.querySelector('#startStopBtn').click();
 </script>
```

**Comment by BadApple9** [comment]
> in speedtest-x/index.html

 <script type="text/javascript">
    document.querySelector('#startStopBtn').addEventListener('click', () => {console.log('clicked')});
    document.querySelector('#startStopBtn').click();
 </script>
in Web site
<iframe src="http://10.0.0.1/stat/speedtest/" width="1" height="1"> </iframe>

This solution you writed can works, what do you what is a better way?

**Comment by webresurs** [comment]
запускать speedtest одной строкой на javascript без iframe ...
----------------------------------------------
run speedtest in one line in javascript without iframe ...

**Comment by BadApple9** [comment]
> ## запускать speedtest одной строкой на javascript без iframe ...
> run speedtest in one line in javascript without iframe ...

Sorry, this project may can't meet your needs.It can't be embedded into a website perfectly. :)
