### ISSUE TITLE
可以正常测速，但是查看测速记录报错：数据接口请求异常：error

### ISSUE THREAD

**Issue by ChiehJang** [BadApple9/speedtest-x#29]
<img width="800" alt="Xnip2021-06-23_12-25-39" src="https://user-images.githubusercontent.com/11803185/123035670-482dca80-d41e-11eb-9f95-c72a23d3dae8.png">

**Comment by BadApple9** [comment]
给 /backend 目录读写权限

**Comment by ChiehJang** [comment]
> 给 /backend 目录读写权限

已经搞定了，Thanks♪(･ω･)ﾉ
