### ISSUE TITLE
[new feature]单IP多次测试只记录一条

### ISSUE THREAD

**Issue by mzhboy** [BadApple9/speedtest-x#3]
在不同时间测试速度，希望能记下每次的速度和时间，但是只有最后一条记录。
希望至少能加个开关允许相同ip记录多次（可以设置时间间隔什么的）

----------

可能恶意刷流量那个是不是可以考虑将最大值限死

**Comment by BadApple9** [comment]
感谢你的关注。

你提的建议我已经收到，计划在下一次更新中增加单 IP 储存多条记录的可配置项。

关于恶意刷流量的问题，理论上最大值限死的方式是无用的。即使限制得很小，恶意访客始终可以通过单IP多线程、多IP多线程等方式不断请求下行测试文件，达到刷流量的效果。
**但我会在下个版本将单文件最大尺寸调整至 100M（源项目单文件限制 1024M）。**

**Comment by BadApple9** [comment]
Hi，

我在 [c07f863
](https://github.com/BadApple9/speedtest-x/commit/c07f8630eeb42350365fbe31f10972745c0f3ba2) 提交中已经将下行测速文件最大尺寸调整到 50M。

当「增加单 IP 储存多条记录的可配置项」功能发布后，我会关闭这个 issue。

再次感谢。

**Comment by mzhboy** [comment]
考虑把主键换成时间如何

**Comment by BadApple9** [comment]
> 考虑把主键换成时间如何

感谢建议，这两天已经开始动工了，由前端生成一段字符串来做唯一性区分。

**Comment by BadApple9** [comment]
此功能已经在 [20201210 release](https://github.com/BadApple9/speedtest-x/releases/tag/20201210) 添加，或者直接拉取最新的 docker 镜像进行配置。

具体配置参数请参考 readme。
