### ISSUE TITLE
为什么这个版本比原版本测试表现好？

### ISSUE THREAD

**Issue by leechaowen** [BadApple9/speedtest-x#30]
在同一台机器(ubuntu 16.04) 用docker 部署，测试

docker pull badapple9/speedtest-x
docker run -d --restart=always --name speedtest -p 9001:80 -it badapple9/speedtest-x

docker pull adolfintel/speedtest
docker run -d --restart=always -p 8080:80 adolfintel/speedtest:latest

firefox 打开：
http://127.0.0.1:9001
http://127.0.0.1:8080 

为什么这个版本 speedtest-x 比原版本测试 speedtest 表现好？作了什么改进？ 有空可以介绍下吗？谢谢。

**Comment by BadApple9** [comment]
比较玄学的问题，表现好是好多少呢？差异大吗？

相比原项目的下载测速，我这边限制了单文件的最大尺寸，其他的没改动。但是按道理说和这个没什么关系。
