### ISSUE TITLE
同IP多条记录的问题

### ISSUE THREAD

**Issue by nickonline2005** [BadApple9/speedtest-x#31]
测试发现，如果想同IP记录多条测速结果，那么下次测速开始前必须刷新页面后再测速才能记录到新的测速结果，如果不刷新页面就再次测速则永远只记录最近一次的测速结果（测速记录只有一条）。请问这是属于bug还是就这样设计的？

**Comment by BadApple9** [comment]
是故意为之。

测速程序会在用户打开页面时生成唯一访客ID，未刷新网页访客ID是一致的。

**Comment by mzhboy** [comment]
关于这个功能，对我来说不太友好，回退到 20201210 版。
简要说明：我经常开一个页面留很长时间，如果开一天页面都不关闭，且在一天的多个时间测试，则只会留下最后一条记录，这样就不方便了。
如果可以的话，希望加个开关。因为自己的地址未公开基本上只有自己访问。
