### ISSUE TITLE
本地部署运营商与地区显示Unknown

### ISSUE THREAD

**Issue by hzx8848** [BadApple9/speedtest-x#33]
github下载到本地再通过宝塔上传到了网站目录，内核为debian10 自带内核 Debian GNU/Linux 10 KVM x86_64 4.19.0-17-amd64，在另一台vps上也出现了同样的问题

**Comment by hzx8848** [comment]
两个ip库都不行

**Comment by yiguihai** [comment]
数据接口请求异常：parsererror  
你不是一个人

**Comment by eyesinwind** [comment]
遇到同样情况，PHP安全里面允许allow_url_fopen即可解决。

**Comment by hzx8848** [comment]
已解决，感谢大佬！

> 遇到同样情况，PHP安全里面允许allow_url_fopen即可解决。
