### ISSUE TITLE
docker 指定参数无效

### ISSUE THREAD

**Issue by tricklin77** [BadApple9/speedtest-x#38]
docker 启动指定参数没用 
docker run -e MAX_LOG_COUNT=1000 -e IP_SERVICE=ip.sb -e SAME_IP_MULTI_LOGS=true -e WEBPORT=86 --name speedtest -it -d -p 9994:86 -it badapple9/speedtest-x
没一个-e参数起作用

**Comment by BadApple9** [comment]
我测试了，是起作用的，你说的不起作用表现在哪里？有截图吗？

**Comment by tricklin77** [comment]
启动后还是80端口

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bad Apple!! ***@***.***&gt;
发送时间: 2022年1月12日 11:06
收件人: BadApple9/speedtest-x ***@***.***&gt;
抄送: tricklin77 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [BadApple9/speedtest-x] docker 指定参数无效 (Issue #38)





 
我测试了，是起作用的，你说的不起作用表现在哪里？有截图吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BadApple9** [comment]
按照你的启动命令，启动后是监听9994端口，也不是80呀。

**Comment by tricklin77** [comment]
webport不是指定使用的端口吗
我80要留着其他用 按你的参数我指定webport为9994
但是启动后speedtest还是用的80端口
-e webport不就是不起作用？

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bad Apple!! ***@***.***&gt;
发送时间: 2022年1月12日 11:37
收件人: BadApple9/speedtest-x ***@***.***&gt;
抄送: tricklin77 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [BadApple9/speedtest-x] docker 指定参数无效 (Issue #38)





 
按照你的启动命令，启动后是监听9994端口，也不是80呀。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BadApple9** [comment]
-e WEBPORT影响的是容器内的监听端口，注意，容器内即使监听80，也不会和容器外的80冲突。容器外监听的是9994端口，9994会转发到容器内的86

你说的启动后用的80端口，那肯定不是你运行的这个容器监听的，请注意检查服务器的应用或者其他容器是否有占用80

**Comment by tricklin77** [comment]
我再研究下 其他参数在容器中的配置文件确实能看到
