### ISSUE TITLE
查看测速记录显示：数据接口请求异常：parsererror

### ISSUE THREAD

**Issue by jamespan2012** [BadApple9/speedtest-x#40]
Debian 10系统，apt命令安装的nginx和php7.3
`apt update && apt install php php-fpm curl tar nginx -y`
查看测速记录显示：数据接口请求异常：parsererror，查看线性图表则显示：Can't get data。
宝塔同版本的php则可以正常显示测速记录。
Nginx配置文件中php部分如下
```
location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.3-fpm.sock;
    }
```
是否是php缺了某个扩展？还是其他原因导致的错误

**Comment by FaithPatrick** [comment]
给 /backend 目录读写权限。

**Comment by BadApple9** [comment]
赋予 backend 目录读写权限。
