### ISSUE TITLE
docker 无法获取IP地址

### ISSUE THREAD

**Issue by oneg1** [BadApple9/speedtest-x#41]
显示 IP地址: 10.202.0.1 - private IPv4 access
docker启动命令 
`docker run -d -e WEBPORT=22111 --net=host -p 22111:22111 -it badapple9/speedtest-x`
机器是NAT的VPS 
测速地址：http://80.78.132.239:22111/

**Comment by BadApple9** [comment]
尝试不使用 host 网络模式试一下。

`docker run -d -e WEBPORT=22111 -p 22111:22111 -it badapple9/speedtest-x`

**Comment by oneg1** [comment]
> 尝试不使用 host 网络模式试一下。
> 
> `docker run -d -e WEBPORT=22111 -p 22111:22111 -it badapple9/speedtest-x`

试过了也是一样
![image](https://user-images.githubusercontent.com/31442507/160800454-75f212c7-da8e-4b2e-b38d-755db21ea0bc.png)

**Comment by oneg1** [comment]
> 尝试不使用 host 网络模式试一下。
> 
> `docker run -d -e WEBPORT=22111 -p 22111:22111 -it badapple9/speedtest-x`

![image](https://user-images.githubusercontent.com/31442507/160800765-8436cc9a-a147-49fb-b5e8-649b6ea8012a.png)

**Comment by BadApple9** [comment]
刚看到是 NAT 的 VPS，如果该 NAT 机器没有在网关层传递源 IP 的话，是拿不到正确的来源 IP 的。

**Comment by oneg1** [comment]
> 刚看到是 NAT 的 VPS，如果该 NAT 机器没有在网关层传递源 IP 的话，是拿不到正确的来源 IP 的。

好的
