### ISSUE TITLE
能否定制页面 标题文字 “speedtest-x” 

### ISSUE THREAD

**Issue by tanpengsccd** [BadApple9/speedtest-x#42]
能否定制页面 标题文字 “speedtest-x” ,比如 “搬瓦工 CN2 测速”

**Comment by BadApple9** [comment]
有这个需求可自行修改标题。

**Comment by luckiestone** [comment]
> 有这个需求可自行修改标题。

请问Docker内如何更方便修改？是否可以增加这个环境变量，或者增加一个配置文件？
