### ISSUE TITLE
提问:speedtest-x测速时无法查到ip位置

### ISSUE THREAD

**Issue by Altria002** [BadApple9/speedtest-x#44]
![image](https://user-images.githubusercontent.com/53386594/176981415-8c6604c3-5579-4f04-9c13-2a2cb37d26d1.png)
如图所示，测速时无法正确显示测速的位置。
配置:ubuntu bt

**Comment by BadApple9** [comment]
没有实际的服务器环境，我也没办法排查这个问题。。
