### ISSUE TITLE
测速数据库没有数据

### ISSUE THREAD

**Issue by hjkl950217** [BadApple9/speedtest-x#47]
如图... 
![image](https://user-images.githubusercontent.com/11371470/181009417-33de8c8b-622c-45f9-b5aa-f5420ee9ff0d.png)

使用的docker镜像是 stilleshan/speedtest-x,没有开映射文件什么的。。
环境变量配置：
```
    environment: #设置容器内的环境变量 会覆盖镜像中的环境变量
      - WEBPORT=10090 #最大可保存多少条测速记录
      - MAX_LOG_COUNT=100 #最大可保存多少条测速记录
      - IP_SERVICE=ip.sb #使用的 IP 运营商解析服务(ip.sb 或 ipinfo.io)
      - SAME_IP_MULTI_LOGS=true #是否允许同一IP记录多条测速结果
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
```

**Comment by BadApple9** [comment]
ARM 镜像 stilleshan/speedtest-x 是网友维护，他的镜像代码可能不是最新代码。
出错原因是 speedteest-x 之前使用的字节跳动 CDN 有 BUG，导致 JS 加载有错误，不能正常显示数据表格。

现在已经替换新的 CDN，我会制作一份新的 ARM 镜像，上传后会在本 issue 通知。

**Comment by hjkl950217** [comment]
@BadApple9  非常感谢~

**Comment by BadApple9** [comment]
有道理，之前没有研究过 docker 同时构建多平台镜像，我研究下。

**Comment by hjkl950217** [comment]
其实不用。。就是代码放在一个仓库里。。准备2份dockerFile文件就好拉。。 这样就同时维护了，避免这种版本不一致。  如果走github 的actions构建的话。。他本身就能配置多个任务，跑2次就O拉

**Comment by BadApple9** [comment]
> 其实不用。。就是代码放在一个仓库里。。准备2份dockerFile文件就好拉。。 这样就同时维护了，避免这种版本不一致。 如果走github 的actions构建的话。。他本身就能配置多个任务，跑2次就O拉

我研究了下，好像也不用两份 dockerfile，用 docker 的 `buildx` 命令直接就可以构建多平台镜像了。 
回头考虑用 GitHub 的 actions 来构建。

我已推送同时支持 linux/amd64 和 linux/arm64 的镜像，你可以直接使用 `docker pull badapple9/speedtest-x` 拉取了。
