### ISSUE TITLE
结果页仍然不能显示

### ISSUE THREAD

**Issue by luckiestone** [BadApple9/speedtest-x#55]
拉取的是最新的docker镜像，但是并没有解决问题 https://github.com/BadApple9/speedtest-x/issues/47 
查看`results.html`  34行内为`https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/layui/2.5.7/layui.js`，尝试通过映射`/var/www/html`到宿主机，更改34行内为`https://www.layuicdn.com/layui/layui.js`(该链接有效)，但是容器重启后宿主机的`results.html`会被重置。

**Comment by BadApple9** [comment]
你拉取的并不是最新镜像。

最新镜像的 `results.html` 中已不包含 `https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/layui/2.5.7/layui.js` 该资源。

请贴一下您的镜像拉取命令。

**Comment by luckiestone** [comment]
docker run -dit --restart always --name speedtest-x -p 18080:80 -v /root/speedtestx/html:/var/www/html -it badapple9/speedtest-x

**Comment by BadApple9** [comment]
> docker run -dit --restart always --name speedtest-x -p 18080:80 -v /root/speedtestx/html:/var/www/html -it badapple9/speedtest-x

这个是容器运行命令，我猜测您本地的镜像可能是以前的镜像，你可以运行 `docker image list` 查看一下镜像的创建时间。

**Comment by BadApple9** [comment]
> 我是容器运行直接拉取的，这个机器是今年底才安装的，按理说拉取的肯定是最新的。但是`docker image list`为： `badapple9/speedtest-x latest 5151bb58fbaa 14 months ago 495MB` `docker pull`又显示最新：
> 
> ```
> latest: Pulling from badapple9/speedtest-x
> Digest: sha256:9ae8a9ce6c30bd5629bd27923fdfea5718918ef244699c7f3be338de2da45ecd
> Status: Image is up to date for badapple9/speedtest-x:latest
> docker.io/badapple9/speedtest-x:latest
> ```

删除现有镜像 `docker rmi 5151bb58fbaa `，并重新拉取 `docker pull badapple9/speedtest-x:latest` 试试

**Comment by luckiestone** [comment]
非常感谢，尝试了各种方式包括rmi删除再pull，最终发现是docker镜像源的问题，把镜像源删了就能拉到新的了。
