### ISSUE TITLE
测速没有速度，求解

### ISSUE THREAD

**Issue by gpronhub** [BadApple9/speedtest-x#57]
在一个vps服务器（Ubuntu 18.04 with Docker）上安装speedtestx，测速时延迟很大（几百ms），上行只有1Mbps，为啥啊？

**Comment by BadApple9** [comment]
使用 host 网络模式启动容器试试：
`docker run -d -p 9001:80 -it badapple9/speedtest-x --net=host`

**Comment by gpronhub** [comment]
> 使用 host 网络模式启动容器试试： `docker run -d -p 9001:80 -it badapple9/speedtest-x --net=host

提升：
root@racknerd-febab6:~# docker run -d -p 9001:80 -it badapple9/speedtest-x --net=host
b58ba8284867fc6a58bde0abae07a041de9355419c976144cbe150e070c921e2
docker: Error response from daemon: driver failed programming external connectivity on endpoint distracted_hodgkin (6011a89d1f8a88a0c23d5e663f534a16500d97796ad39abd3a4134ef22d45985): Bind for 0.0.0.0:9001 failed: port is already allocated.

**Comment by BadApple9** [comment]
> > 使用 host 网络模式启动容器试试： `docker run -d -p 9001:80 -it badapple9/speedtest-x --net=host
> 
> 提示： root@racknerd-febab6:~# docker run -d -p 9001:80 -it badapple9/speedtest-x --net=host b58ba8284867fc6a58bde0abae07a041de9355419c976144cbe150e070c921e2 docker: Error response from daemon: driver failed programming external connectivity on endpoint distracted_hodgkin (6011a89d1f8a88a0c23d5e663f534a16500d97796ad39abd3a4134ef22d45985): Bind for 0.0.0.0:9001 failed: port is already allocated.

先停掉当前正在运行的容器。

**Comment by gpronhub** [comment]
Forbidden
You don't have permission to access this resource.
Apache/2.4.54 (Debian) Server at 108.166.195.73 Port 9001

显示这个，但是我已经放行了9001端口了啊

**Comment by BadApple9** [comment]
> Forbidden You don't have permission to access this resource. Apache/2.4.54 (Debian) Server at 108.166.195.73 Port 9001
> 
> 显示这个，但是我已经放行了9001端口了啊

会不会是服务器的延迟本来就是几百ms呀？
通过这个表单 https://forms.gle/KN7oHoXfEQ4acLLY7 把测速地址发我看下

**Comment by gpronhub** [comment]
> 

IP地址吗？

**Comment by gpronhub** [comment]
发了

**Comment by BadApple9** [comment]
> 发了

你先把测速程序正常跑起来，先别用 --net=host 模式。

**Comment by BadApple9** [comment]
> 跑出来了，只是延迟还是200多ms，而且速度很慢我是联通1000m ![Snipaste_2023-08-21_16-30-54](https://user-images.githubusercontent.com/101042752/261966334-e80275c5-5029-498f-80f4-ab23fe7ddd16.png)

我感觉这个结果很正常呀，首先1000m的宽带下载和上传是不对等的，上传带宽往往只有30~50Mpbs左右，加上梯子线路(比如去程线路不是很好)的损耗，上传速度在几兆和几十兆之间波动是正常的。

看你的这个结果没什么问题的。（最起码和测试程序关系不大）

**Comment by gpronhub** [comment]
ok 谢谢大佬
