### ISSUE TITLE
似乎无法测速

### ISSUE THREAD

**Issue by BlueSkyXN** [BadApple9/speedtest-x#9]
IP识别显示400
测速记录显示数据接口error
下载速度0
上传正常
Ping和抖动正常

**Comment by BlueSkyXN** [comment]
哦。可能是我错误把body写坏了，重新恢复一下就好了QAQ

**Comment by BlueSkyXN** [comment]
但是数据接口还是不对，查不了记录

[https://p.pstatp.com/origin/137da0002e6aefecfc9c9](url)

**Comment by BadApple9** [comment]
你好，能否将你部署的测速地址和具体的报错截图，发送到 `v5@outlook.at`

我排查一下。

**Comment by BlueSkyXN** [comment]
> 你好，能否将你部署的测速地址和具体的报错截图，发送到 `v5@outlook.at`
> 
> 我排查一下。

现在好像好了，可能是缓存没处理干净吧QAQ

**Comment by BadApple9** [comment]
> > 你好，能否将你部署的测速地址和具体的报错截图，发送到 `v5@outlook.at`
> > 我排查一下。
> 
> 现在好像好了，可能是缓存没处理干净吧QAQ

好的，有问题欢迎继续提 issue 给我。
